#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ENV=$1
if [ $ENV = 'test' ]
then
    export ENV=$ENV
    python runserver-tests.py
else
    export ENV=$ENV
    echo $(date) >> $DIR/dev.log
    echo "################################################################################" >> $DIR/dev.log
    python runserver.py >> $DIR/dev.log 2>&1 
    echo "################################################################################" >> $DIR/dev.log
fi
